---
- name: List all running Xen VMs
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Get list of running Xen VMs
      command: xl list
      register: xen_vm_list
      changed_when: false

    - name: Display running VMs
      debug:
        msg: "{{ xen_vm_list.stdout_lines }}"