---
- name: Install WireGuard
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Install WireGuard package
      apt:
        name: wireguard
        state: present

    - name: Create Private Key file
      ansible.builtin.file:
        path: /etc/wireguard/private_key
        state: touch
        mode: 0600
    
    - name: Generate WireGuard private key
      command: wg genkey
      register: private_key

    - name: Write private key to file
      copy:
        content: "{{ private_key['stdout'] }}"
        dest: /etc/wireguard/private_key

    - name: Create Public Key file
      ansible.builtin.file:
        path: /etc/wireguard/public_key
        state: touch
        mode: 0600

    - name: Generate WireGuard public key
      shell: echo "{{ private_key['stdout'] }}" | wg pubkey
      register: public_key

    - name: Write Public key to file
      copy:
        content: "{{ public_key['stdout'] }}"
        dest: /etc/wireguard/public_key

    - name: Create WireGuard configuration file
      ansible.builtin.copy:
        dest: /etc/wireguard/homelab.conf
        content: |
          [Interface]
          PrivateKey = {{ private_key['stdout'] }}
          Address = {{ vpn_ip }}/24
          MTU = 1280

          [Peer]
          PublicKey = {{ server_public_key }}
          Endpoint = vpn.suuynyuy.com:51820
          AllowedIPs = 10.0.0.0/8
          PersistentKeepalive = 25

    - name: Enable WireGuard Service
      systemd:
        name: wg-quick@homelab
        enabled: yes

    - name: Start WireGuard Service
      systemd:
        name: wg-quick@homelab
        state: started

    - name: Display public key
      command: cat /etc/wireguard/public_key
      register: public_key_output

    - name: Show public key
      debug:
        var: public_key_output.stdout
    
    - name: Display private key
      command: cat /etc/wireguard/private_key
      register: private_key_output

    - name: Show private key
      debug:
        var: private_key_output.stdout
    
    - name: Start WireGuard Interface
      shell: wg-quick up homelab
