---
- name: Install WireGuard
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Install WireGuard package
      apt:
        name: wireguard
        state: present

    - name: Create Private Key file
      ansible.builtin.file:
        path: /etc/wireguard/private_key
        state: file
        mode: 0600
    
    - name: Generate WireGuard private key
      command: "wg genkey > /etc/wireguard/private_key"
      ignore_errors: true

    - name: Create Private Key file
      ansible.builtin.file:
        path: /etc/wireguard/public_key
        state: file
        mode: 0600

    - name: Generate WireGuard public key
      command: "cat /etc/wireguard/private_key | wg pubkey > /etc/wireguard/public_key"
      ignore_errors: true

    - name: Create WireGuard configuration file
      ansible.builtin.copy:
        dest: /etc/wireguard/homelab.conf
        content: |
          [Interface]
          PrivateKey = {{ lookup('file', '/etc/wireguard/private_key') }}
          Address = {{ vpn_ip }}/24
          MTU = 1280

          [Peer]
          PublicKey = {{ server_public_key }}
          Endpoint = vpn.suuynyuy.com:51820
          AllowedIPs = 10.0.0.0/8
          PersistentKeepalive = 25

    - name: Ensure WireGuard service is enabled and started
      systemd:
        name: wg-quick@homelab
        enabled: yes
        state: started

    - name: Display public key
      command: cat /etc/wireguard/public_key
      register: public_key_output

    - name: Show public key
      debug:
        var: public_key_output.stdout
    
    - name: Display private key
      command: cat /etc/wireguard/private_key
      register: private_key_output

    - name: Show private key
      debug:
        var: private_key_output.stdout
