---
- name: List running containers on servers
  hosts: all
  gather_facts: false
  tasks:
    - name: Get list of running containers
      community.docker.docker_host_info:
        containers: true
      register: docker_info

    - name: Display running containers
      debug:
        msg: "{{ docker_info }}"