---
- name: List running containers on servers
  hosts: all
  gather_facts: false
  tasks:
    - name: Get list of running containers
      community.docker.docker_host_info:
        containers: true
      register: docker_info

    - name: Display running containers
      debug:
        msg: |
          Image: {{ item.Image }}
          Status: {{ item.Status }}
          Ports: {{ item.Ports | map(attribute='PublicPort') | select('defined') | list | join(', ') }}
      loop: "{{ docker_info.containers | list }}"
      when: docker_info.containers | list | length > 0

    - name: No running containers found
      debug:
        msg: "No running containers found on {{ inventory_hostname }}"
      when: docker_info.containers | list | length == 0