---
- name: Create new VM
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Create VM Directory
      file:
        path: "{{ vm_path }}/{{ vm_name }}"
        state: directory
        owner: root
        group: root
    
    - name: Copy Template Disk Image
      copy:
        src: "{{ vm_path }}/{{ vm_template }}/template_disk.img"
        dest: "{{ vm_path }}/{{ vm_name }}/{{ vm_name }}.img"
        owner: root
        group: root
        delegate_to: "{{ inventory_hostname }}"
    
    - name: Create VM Config File
      copy:
        content: |
          name = "\"{{ vm_name }}\""
          memory = {{ vm_memory }}
          vcpus = {{ vm_vcpus }}
          disk = [ 'file: "{{ vm_path }}/{{ vm_name }}/{{ vm_name }}".img,xvda,w' ]
          vif=[ 'bridge=vmbr0,mac="{{vm_mac}}, ip="{{vm_ip}}/24"' ]
          bootloader="/usr/local/lib/xen/bin/pygrub"

        path: "{{ vm_path }}/{{ vm_name }}/{{ vm_name }}.cfg"
        state: touch
        owner: root
        group: root
        mode: '0644'

    - name: Start VM
      command: "xl create {{ vm_path }}/{{ vm_name }}/{{ vm_name }}.cfg"
      args:
        chdir: "{{ vm_path }}/{{ vm_name }}"
      register: start_vm_result
      ignore_errors: true
    
    - name: Check if VM started successfully
      debug:
        msg: "VM {{ vm_name }} started successfully."
      when: start_vm_result.rc == 0