---
- name: Update and upgrade Ubuntu servers
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      command: apt update

    - name: Upgrade all packages
      command: apt upgrade -y
