---
- name: Update and upgrade Debian server
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes
